---

- name: Set Distro Variables
  include_vars: '{{ item }}'
  with_first_found:
    - '{{ ansible_os_family }}.yml'
    - default.yml

- name: Set Hosts
  set_fact:
    keystone_host: "{{ [keystone.host, common.controller_host] | first_found | default('127.0.0.1') }}"
    keystone_hosts: "{{ [keystone.hosts, common.controller_hosts] | first_found | default(['127.0.0.1']) }}"
    keystone_version: "{{ keystone.version | default(['v2.0']) }}"
    glance_host: "{{ [glance.host, common.controller_host] | first_found | default('127.0.0.1') }}"
    glance_hosts: "{{ [glance.hosts, common.controller_hosts] | first_found | default(['127.0.0.1']) }}"
    cinder_host: "{{ [cinder.host, common.controller_host] | first_found | default('127.0.0.1') }}"
    cinder_hosts: "{{ [cinder.hosts, common.controller_hosts] | first_found | default(['127.0.0.1']) }}"
    neutron_host: "{{ [neutron.host, common.controller_host] | first_found | default('127.0.0.1') }}"
    neutron_hosts: "{{ [neutron.hosts, common.controller_hosts] | first_found | default(['127.0.0.1']) }}"
    nova_host: "{{ [nova.host, common.controller_host] | first_found | default('127.0.0.1') }}"
    nova_hosts: "{{ [nova.hosts, common.controller_hosts] | first_found | default(['127.0.0.1']) }}"
    heat_host: "{{ [heat.host, common.controller_host] | first_found | default('127.0.0.1') }}"
    heat_hosts: "{{ [heat.hosts, common.controller_hosts] | first_found | default(['127.0.0.1']) }}"
    ceilometer_host: "{{ [ceilometer.host, common.controller_host] | first_found | default('127.0.0.1') }}"
    ceilometer_hosts: "{{ [ceilometer.hosts, common.controller_hosts] | first_found | default(['127.0.0.1']) }}"
    swift_host: "{{ [swift.host, common.controller_host] | first_found | default('127.0.0.1') }}"
    swift_hosts: "{{ [swift.hosts, common.controller_hosts] | first_found | default(['127.0.0.1']) }}"
    horizon_host: "{{ [horizon.host, common.controller_host] | first_found | default('127.0.0.1') }}"
    horizon_hosts: "{{ [horizon.hosts, common.controller_hosts] | first_found | default(['127.0.0.1']) }}"
    mysql_host: "{{ [mysql.host, common.controller_host] | first_found | default('127.0.0.1') }}"
    mysql_hosts: "{{ [mysql.hosts, common.controller_hosts] | first_found | default(['127.0.0.1']) }}"
    rabbit_hosts: "{{ common.rabbit_hosts | append(':5672') | join(',') }}"
    aodh_host: "{{ [common.aodh_host, common.controller_host] | first_found | default('127.0.0.1') }}"
    redis_host: "{{ [common.redis_host, common.controller_host] | first_found | default('127.0.0.1') }}"
    redis_hosts: "{{ [redis.hosts, common.controller_hosts] | first_found | default(['127.0.0.1']) }}"
    designate_host: "{{ [common.designate_host, common.controller_host] | first_found | default('127.0.0.1') }}"
    designate_hosts: "{{ [common.designate_hosts, common.controller_hosts] | first_found | default(['127.0.0.1']) }}"
    bind_host: "{{ [designate.bind_host, common.bind_host, common.controller_host] | first_found | default('127.0.0.1') }}"
    magnum_host: "{{ [common.magnum_host, common.controller_host] | first_found | default('127.0.0.1') }}"
    magnum_hosts: "{{ [common.magnum_hosts, common.controller_hosts] | first_found | default(['127.0.0.1']) }}"

- name: Force Keystone Version to v2.0
  set_fact:
    #keystone_version: "{{ keystone.version | default('v2.0') }}"
    keystone_version: "v2.0"

- name: Set Openstack Variables
  set_fact:
    version: "{{ common.version | default('latest') }}"
    keystone_public_url: "{{ keystone.public_url | default('http://' ~ keystone_host ~ ':5000/' ~ keystone_version) }}"
    keystone_internal_url: "{{ keystone.internal_url | default('http://' ~ keystone_host ~ ':5000/' ~ keystone_version) }}"
    keystone_admin_url: "{{ keystone.admin_url | default('http://' ~ keystone_host ~ ':35357/' ~ keystone_version) }}"
    keystone_identity_uri: "{{ 'http://' ~ keystone_host ~ ':35357' }}"
    glance_public_url: "{{ glance.public_url | default('http://' ~ glance_host ~ ':9292') }}"
    glance_internal_url: "{{ glance.internal_url | default('http://' ~ glance_host ~ ':9292') }}"
    glance_admin_url: "{{ glance.admin_url | default('http://' ~ glance_host ~ ':9292') }}"
    glance_api_servers: "{{ [glance.hosts, common.glance_hosts] | first_found | default(['127.0.0.1']) }}"
    cinder_public_url: "{{ cinder.public_url | default('http://' ~ cinder_host ~ ':8776/v1/%(tenant_id)s') }}"
    cinder_internal_url: "{{ cinder.internal_url_v2 | default('http://' ~ cinder_host ~ ':8776/v1/%(tenant_id)s') }}"
    cinder_admin_url: "{{ cinder.admin_url | default('http://' ~ cinder_host ~ ':8776/v1/%(tenant_id)s') }}"
    cinderv2_public_url: "{{ cinder.public_url_v2 | default('http://' ~ cinder_host ~ ':8776/v2/%(tenant_id)s') }}"
    cinderv2_internal_url: "{{ cinder.internal_url_v2 | default('http://' ~ cinder_host ~ ':8776/v2/%(tenant_id)s') }}"
    cinderv2_admin_url: "{{ cinder.admin_url_v2 | default('http://' ~ cinder_host ~ ':8776/v2/%(tenant_id)s') }}"
    neutron_public_url: "{{ neutron.public_url | default('http://' ~ neutron_host ~ ':9696') }}"
    neutron_internal_url: "{{ neutron.internal_url | default('http://' ~ neutron_host ~ ':9696') }}"
    neutron_admin_url: "{{ neutron.admin_url | default('http://' ~ neutron_host ~ ':9696') }}"
    neutron_core_plugin: "{{ neutron.core_plugin | default('ml2') }}"
    neutron_service_plugins: "{{ neutron.service_plugins | default(['router']) }}"
    neutron_tenant_type: "{{ neutron.tenant_type | default('vxlan') }}"
    neutron_network_vlan_ranges: "{{ neutron.network_vlan_ranges | default('physnet1:1000:2999,physnet2:3000:3999') }}"
    neutron_type_drivers: "{{ neutron.type_drivers | default(['local,flat,vlan,gre,vxlan']) }}"
    neutron_mechanism_drivers: "{{ neutron.mechanism_drivers | default(['openvswitch']) }}"
    neutron_tunnel_ip: "{{ hostvars[inventory_hostname]['ansible_'+(neutron.tunnel_interface | default('eth0'))]['ipv4']['address'] }}"
    nova_public_url: "{{ nova.public_url | default('http://' ~ nova_host ~ ':8774/v2/%(tenant_id)s') }}"
    nova_internal_url: "{{ nova.internal_url | default('http://' ~ nova_host ~ ':8774/v2/%(tenant_id)s') }}"
    nova_url: "http://{{ nova_host }}:8774/v2"
    nova_vnc_ip: "{{ hostvars[inventory_hostname]['ansible_'+(nova.vnc_interface | default('eth0'))]['ipv4']['address'] }}"
    novncproxy_url: "{{ nova.novncproxy_url | default('http://' ~ nova_host ~ ':6080/vnc_auto.html') }}"
    nova_ceilometer: "{{ nova.ceilometer | default('False')  | bool }}"
    nova_admin_url: "{{ nova.admin_url | default('http://' ~ nova_host ~ ':8774/v2/%(tenant_id)s') }}"
    heat_public_url: "{{ heat.public_url | default('http://' ~ heat_host ~ ':8004/v1/%(tenant_id)s') }}"
    heat_internal_url: "{{ heat.internal_url | default('http://' ~ heat_host ~ ':8004/v1/%(tenant_id)s') }}"
    heat_admin_url: "{{ heat.admin_url | default('http://' ~ heat_host ~ ':8004/v1/%(tenant_id)s') }}"
    heat_cfn_public_url: "{{ heat.public_url | default('http://' ~ heat_host ~ ':8000/v1') }}"
    heat_cfn_internal_url: "{{ heat.internal_url | default('http://' ~ heat_host ~ ':8000/v1') }}"
    heat_cfn_admin_url: "{{ heat.admin_url | default('http://' ~ heat_host ~ ':8000/v1') }}"
    ceilometer_public_url: "{{ ceilometer.public_url | default('http://' ~ ceilometer_host ~ ':8777') }}"
    ceilometer_internal_url: "{{ ceilometer.internal_url | default('http://' ~ ceilometer_host ~ ':8777') }}"
    ceilometer_admin_url: "{{ ceilometer.admin_url | default('http://' ~ ceilometer_host ~ ':8777') }}"
    mongodb_servers: "{{ ceilometer.mongodb_servers| prepend(ceilometer.dbuser+':'+ceilometer.dbpassword+'@') | append(':27017') | join(',') }}"
    ceilometer_db_name: "{{ ceilometer.db_name| default('ceilometer') }}"
    swift_public_url: "{{ swift.public_url | default('http://' ~ swift_host ~ ':8080/v1/AUTH_%(tenant_id)s') }}"
    swift_internal_url: "{{ swift.internal_url | default('http://' ~ swift_host ~ ':8080/v1/AUTH_%(tenant_id)s') }}"
    swift_admin_url: "{{ swift.admin_url | default('http://' ~ swift_host ~ ':8080') }}"
    swift_fstype: "{{ swift.fstype | default('xfs')}}"
    swift_prefix: "{{ swift.prefix | default('ee83091ec3680190d215')}}"
    swift_suffix: "{{ swift.suffix | default('ee83091ec3680190d215')}}"
    swift_partition: "{{ swift.partition | default('16') }}"
    swift_replicas: "{{ swift.replicas | default('3') }}"
    swift_storage_nodes: "{{ swift.storage_nodes | default(['127.0.0.1']) }}"
    aodh_public_url: "{{ aodh.public_url | default('http://' ~ aodh_host ~ ':8042') }}"
    aodh_internal_url: "{{ aodh.internal_url | default('http://' ~ aodh_host ~ ':8042') }}"
    aodh_admin_url: "{{ aodh.admin_url | default('http://' ~ aodh_host ~ ':8042') }}"
    designate_public_url: "{{ designate.public_url | default('http://' ~ designate_host ~ ':9001') }}"
    designate_internal_url: "{{ designate.internal_url | default('http://' ~ designate_host ~ ':9001') }}"
    designate_admin_url: "{{ designate.admin_url | default('http://' ~ designate_host ~ ':9001') }}"
    magnum_public_url: "{{ magnum.public_url | default('http://' ~ magnum_host ~ ':9511/v1') }}"
    magnum_internal_url: "{{ magnum.internal_url | default('http://' ~ magnum_host ~ ':9511/v1') }}"
    magnum_admin_url: "{{ magnum.admin_url | default('http://' ~ magnum_host ~ ':9511/v1') }}"

- name: Set Mysql Prefix for Kilo
  set_fact:
    mysql_prefix: "mysql"
  when: version == 'kilo'

- name: Set Mysql Prefix
  set_fact:
    mysql_prefix: "mysql+pymysql"
  when: version != 'kilo'

#- name: Debug Openstack Variables
#  debug:
#   var: hostvars[inventory_hostname]
#   var: keystone_internal_url
#  when: common.debug is True
